name: 'Documentor Generation'
description: 'Automatically generate accurate documentation for your codebase using Documentor AI.'
inputs:
  model:
    description: 'LiteLLM compatible model to use'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.model }}
